# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oliver/Desktop/OLD_DESKTOP_2/OLD_DESKTOP/PROJECT/THAT_THING

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oliver/Desktop/OLD_DESKTOP_2/OLD_DESKTOP/PROJECT/THAT_THING

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"libassimp3.0-r1270-OGLtuts\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oliver/Desktop/OLD_DESKTOP_2/OLD_DESKTOP/PROJECT/THAT_THING/CMakeFiles /home/oliver/Desktop/OLD_DESKTOP_2/OLD_DESKTOP/PROJECT/THAT_THING/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oliver/Desktop/OLD_DESKTOP_2/OLD_DESKTOP/PROJECT/THAT_THING/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Projector.run

# Build rule for target.
Projector.run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Projector.run
.PHONY : Projector.run

# fast build rule for target.
Projector.run/fast:
	$(MAKE) -f CMakeFiles/Projector.run.dir/build.make CMakeFiles/Projector.run.dir/build
.PHONY : Projector.run/fast

#=============================================================================
# Target rules for targets named ANTTWEAKBAR_116_OGLCORE_GLFW

# Build rule for target.
ANTTWEAKBAR_116_OGLCORE_GLFW: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ANTTWEAKBAR_116_OGLCORE_GLFW
.PHONY : ANTTWEAKBAR_116_OGLCORE_GLFW

# fast build rule for target.
ANTTWEAKBAR_116_OGLCORE_GLFW/fast:
	$(MAKE) -f libs/CMakeFiles/ANTTWEAKBAR_116_OGLCORE_GLFW.dir/build.make libs/CMakeFiles/ANTTWEAKBAR_116_OGLCORE_GLFW.dir/build
.PHONY : ANTTWEAKBAR_116_OGLCORE_GLFW/fast

#=============================================================================
# Target rules for targets named GLEW_190

# Build rule for target.
GLEW_190: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GLEW_190
.PHONY : GLEW_190

# fast build rule for target.
GLEW_190/fast:
	$(MAKE) -f libs/CMakeFiles/GLEW_190.dir/build.make libs/CMakeFiles/GLEW_190.dir/build
.PHONY : GLEW_190/fast

#=============================================================================
# Target rules for targets named GLFW_303

# Build rule for target.
GLFW_303: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GLFW_303
.PHONY : GLFW_303

# fast build rule for target.
GLFW_303/fast:
	$(MAKE) -f libs/glfw-3.0.3/src/CMakeFiles/GLFW_303.dir/build.make libs/glfw-3.0.3/src/CMakeFiles/GLFW_303.dir/build
.PHONY : GLFW_303/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) -f libs/glfw-3.0.3/docs/CMakeFiles/docs.dir/build.make libs/glfw-3.0.3/docs/CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f libs/assimp-3.0.1270/contrib/zlib/CMakeFiles/zlib.dir/build.make libs/assimp-3.0.1270/contrib/zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) -f libs/assimp-3.0.1270/code/CMakeFiles/assimp.dir/build.make libs/assimp-3.0.1270/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named BulletSoftBody

# Build rule for target.
BulletSoftBody: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletSoftBody
.PHONY : BulletSoftBody

# fast build rule for target.
BulletSoftBody/fast:
	$(MAKE) -f libs/bullet-2.81-rev2613/src/BulletSoftBody/CMakeFiles/BulletSoftBody.dir/build.make libs/bullet-2.81-rev2613/src/BulletSoftBody/CMakeFiles/BulletSoftBody.dir/build
.PHONY : BulletSoftBody/fast

#=============================================================================
# Target rules for targets named BulletCollision

# Build rule for target.
BulletCollision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletCollision
.PHONY : BulletCollision

# fast build rule for target.
BulletCollision/fast:
	$(MAKE) -f libs/bullet-2.81-rev2613/src/BulletCollision/CMakeFiles/BulletCollision.dir/build.make libs/bullet-2.81-rev2613/src/BulletCollision/CMakeFiles/BulletCollision.dir/build
.PHONY : BulletCollision/fast

#=============================================================================
# Target rules for targets named BulletDynamics

# Build rule for target.
BulletDynamics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletDynamics
.PHONY : BulletDynamics

# fast build rule for target.
BulletDynamics/fast:
	$(MAKE) -f libs/bullet-2.81-rev2613/src/BulletDynamics/CMakeFiles/BulletDynamics.dir/build.make libs/bullet-2.81-rev2613/src/BulletDynamics/CMakeFiles/BulletDynamics.dir/build
.PHONY : BulletDynamics/fast

#=============================================================================
# Target rules for targets named LinearMath

# Build rule for target.
LinearMath: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LinearMath
.PHONY : LinearMath

# fast build rule for target.
LinearMath/fast:
	$(MAKE) -f libs/bullet-2.81-rev2613/src/LinearMath/CMakeFiles/LinearMath.dir/build.make libs/bullet-2.81-rev2613/src/LinearMath/CMakeFiles/LinearMath.dir/build
.PHONY : LinearMath/fast

src/Sprite.o: src/Sprite.cpp.o
.PHONY : src/Sprite.o

# target to build an object file
src/Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/Projector.run.dir/build.make CMakeFiles/Projector.run.dir/src/Sprite.cpp.o
.PHONY : src/Sprite.cpp.o

src/Sprite.i: src/Sprite.cpp.i
.PHONY : src/Sprite.i

# target to preprocess a source file
src/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/Projector.run.dir/build.make CMakeFiles/Projector.run.dir/src/Sprite.cpp.i
.PHONY : src/Sprite.cpp.i

src/Sprite.s: src/Sprite.cpp.s
.PHONY : src/Sprite.s

# target to generate assembly for a file
src/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/Projector.run.dir/build.make CMakeFiles/Projector.run.dir/src/Sprite.cpp.s
.PHONY : src/Sprite.cpp.s

src/Tile.o: src/Tile.cpp.o
.PHONY : src/Tile.o

# target to build an object file
src/Tile.cpp.o:
	$(MAKE) -f CMakeFiles/Projector.run.dir/build.make CMakeFiles/Projector.run.dir/src/Tile.cpp.o
.PHONY : src/Tile.cpp.o

src/Tile.i: src/Tile.cpp.i
.PHONY : src/Tile.i

# target to preprocess a source file
src/Tile.cpp.i:
	$(MAKE) -f CMakeFiles/Projector.run.dir/build.make CMakeFiles/Projector.run.dir/src/Tile.cpp.i
.PHONY : src/Tile.cpp.i

src/Tile.s: src/Tile.cpp.s
.PHONY : src/Tile.s

# target to generate assembly for a file
src/Tile.cpp.s:
	$(MAKE) -f CMakeFiles/Projector.run.dir/build.make CMakeFiles/Projector.run.dir/src/Tile.cpp.s
.PHONY : src/Tile.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Projector.run"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ANTTWEAKBAR_116_OGLCORE_GLFW"
	@echo "... GLEW_190"
	@echo "... GLFW_303"
	@echo "... docs"
	@echo "... zlib"
	@echo "... assimp"
	@echo "... BulletSoftBody"
	@echo "... BulletCollision"
	@echo "... BulletDynamics"
	@echo "... LinearMath"
	@echo "... src/Sprite.o"
	@echo "... src/Sprite.i"
	@echo "... src/Sprite.s"
	@echo "... src/Tile.o"
	@echo "... src/Tile.i"
	@echo "... src/Tile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

